export const INGREDIENTS = [
	// Spices
	['salt'],
	['black pepper'],
	['bay leave', 'bay leaves'],
	['rosemary seed', 'rosemary seeds'],
	['cumin seed', 'cumin seeds'],
	// Vegetables
	['beetroot', 'beetroots', 'red beet', 'red beets', 'beet', 'beets'],
	['bell pepper', 'bell peppers', 'paprika', 'paprikas'],
	['pepper', 'peppers'],
	['cucumber', 'cucumbers'],
	['onion', 'onions'],
	['potato', 'potatoes'],
	['tomato paste'],
	['tomato', 'tomatoes'],
	['olive', 'olives'],
	['eggplant', 'eggplants'],
	['carrot', 'carrots'],
	['chili', 'chilies'],
	['pea', 'peas'],
	['chickpea', 'chickpeas'],
	['bean', 'beans'],
	['pumpkin', 'pumpkins'],
	['squash', 'squashes'],
	['zucchini', 'zucchinis', 'courgette', 'courgettes'],
	[
		'scallion',
		'scallions',
		'green onion',
		'green onions',
		'spring onion',
		'spring onions',
	],
	// Fruits
	[
		'mandarin',
		'mandarins',
		'mandarine',
		'mandarines',
		'tangerine',
		'tangerines',
		'clementine',
		'clementines',
	],
	['apple', 'apples'],
	['apricot', 'apricots'],
	['banana', 'bananas'],
	['blueberry', 'blueberries'],
	['cherry', 'cherries'],
	['cranberry', 'cranberries'],
	['currant', 'currants'],
	['grapefruit', 'grapefruits'],
	['lemon', 'lemons'],
	['lime', 'limes'],
	['orange', 'oranges'],
	['pear', 'pears'],
	['raspberry', 'raspberries'],
	['strawberry', 'strawberries'],
	['nut', 'nuts'],
	['peanut', 'peanuts'],
	['raisin', 'raisins'],
	['almond', 'almonds'],
	['pecan', 'pecans'],
	['fruit', 'fruits'],
	// Diary
	['cheese'],
	// Flours
	['spelt flour'],
	['all-purpose flour', 'all purpose flour', 'flour'],
	['flour'],
	// Misc
	['burger bun', 'burger buns'],
	['egg', 'eggs'],
	['sugar'],
	['noodle', 'noodles'],
	['rice noodle', 'rice noodles'],
	['extra virgin olive oil', 'extra-virgin olive oil'],
];
