export const INGREDIENTS = [
	// Spices
	['salt'],
	['black pepper'],
	['bay leave', 'bay leaves'],
	['rosemary seed', 'rosemary seeds'],
	['cumin seed', 'cumin seeds'],
	['sunflower seed', 'sunflower seeds'],
	['sesame seeds', 'sesame seeds'],
	['pumpkin seed', 'pumpkin seeds', 'pepita', 'pepitas'],
	// Vegetables
	['beetroot', 'beetroots', 'red beet', 'red beets', 'beet', 'beets'],
	['bell pepper', 'bell peppers', 'paprika', 'paprikas'],
	['pepper', 'peppers'],
	['chinese cabbage', 'chinese cabbages'],
	['red cabbage', 'red cabbages'],
	['savoy cabbage', 'savoy cabbages'],
	['white cabbage', 'white cabbages'],
	['cabbage', 'cabbages'],
	['lamb’s lettuce', 'lamb’s lettuces', "lamb's lettuce", "lamb's lettuces"],
	['lettuce', 'lettuces'],
	[
		'broad bean',
		'broad beans',
		'fava bean',
		'fava beans',
		'faba bean',
		'faba beans',
	],
	['green bean', 'green beans'],
	[
		'runner bean',
		'runner beans',
		'scarlet runner bean',
		'scarlet runner beans',
		'multiflora bean',
		'multiflora beans',
		'butter bean',
		'butter beans',
	],
	['bean', 'beans'],
	[
		'sweet corn',
		'sweet corns',
		'sweetcorn',
		'sweetcorns',
		'sugar corn',
		'sugar corns',
		'pole corn',
		'pole corns',
	],
	['corn', 'corns'],
	[
		'scallion',
		'scallions',
		'green onion',
		'green onions',
		'spring onion',
		'spring onions',
	],
	['onion', 'onions'],
	['kohlrabi', 'kohlrabis', 'kohlrabies', 'german turnip'],
	['turnip', 'turnips'],
	['cucumber', 'cucumbers'],
	['pak choi', 'pak choi', 'bok choi', 'pok choi', 'pichay', 'petsay'],
	['potato', 'potatoes'],
	['tomato paste'],
	['tomato', 'tomatoes'],
	['olive', 'olives'],
	['eggplant', 'eggplants', 'aubergine', 'aubergines'],
	['carrot', 'carrots'],
	[
		'mangold',
		'mangolds',
		'chard',
		'chards',
		'swiss chard',
		'swiss chards',
		'silver beet',
		'silver beets',
		'perpetual spinach',
		'perpetual spinaches',
		'beet spinach',
		'beet spinaches',
		'seakale beet',
		'seakale beets',
		'leaf beet',
		'leaf beets',
	],
	['chili', 'chilies'],
	['pea', 'peas'],
	['chickpea', 'chickpeas'],
	['pumpkin', 'pumpkins'],
	['squash', 'squashes'],
	['zucchini', 'zucchinis', 'courgette', 'courgettes'],
	['black radish', 'black radishes'],
	['radish', 'radishes'],
	['chicory', 'chicories'],
	['rutabaga', 'rutabagas', 'swede', 'swedes'],
	['asparagus', ' asparaguses', 'asparagusses', 'asparagi'],
	['mushroom', 'mushrooms'],
	['parsley'],
	['basil'],
	['dill'],
	['garlic'],
	['parsley root', 'parsley roots'],
	['kale', 'kales'],
	['iceberg salad', 'iceberg salad', 'iceberg'],
	['salsify', 'salsifies'],
	['jalapeño', 'jalapeños', 'jalapeno', 'jalapenos'],
	['rhubarb', 'rhubarbs'],
	['spinach', 'spinaches'],
	['broccoli', 'broccolis'],
	['celery', 'celeries'],
	['fennel', 'fennels'],
	['rucola', 'rucola', 'rocket', 'rockets', 'arugula', 'arugulas'],
	['cauliflower', 'cauliflowers'],
	['parsnip', 'parsnips', 'pastinak'],
	['celeriac', 'celeriacs', 'celery root', 'celery roots'],
	['brussels sprout', 'brussels sprouts'],
	// Fruits
	[
		'blackcurrant',
		'blackcurrants',
		'black currant',
		'black currants',
		'cassis',
		'cassises',
	],
	['redcurrant', 'redcurrants', 'red currant', 'red currants'],
	['currant', 'currants'],
	[
		'mandarin',
		'mandarins',
		'mandarine',
		'mandarines',
		'tangerine',
		'tangerines',
		'clementine',
		'clementines',
	],
	['apple', 'apples'],
	['apricot', 'apricots'],
	['banana', 'bananas'],
	['blueberry', 'blueberries'],
	['blackberry', 'blackberries'],
	['gooseberry', 'gooseberries'],
	['cherry', 'cherries'],
	['cranberry', 'cranberries'],
	['grapefruit', 'grapefruits'],
	['lemon', 'lemons'],
	['lime', 'limes'],
	['orange', 'oranges'],
	['plum', 'plums'],
	['pear', 'pears'],
	['grape', 'grapes'],
	['quince', 'quinces'],
	['watermelon', 'watermelons'],
	['raspberry', 'raspberries'],
	['strawberry', 'strawberries'],
	['elderberry', 'elderberries', 'elder', 'elders'],
	['nut', 'nuts'],
	['peanut', 'peanuts'],
	['raisin', 'raisins'],
	['almond', 'almonds'],
	['pecan', 'pecans'],
	['fruit', 'fruits'],
	// Diary
	['cheese'],
	// Meat
	['chicken stock', 'chicken broth'],
	['chicken', 'chicken'],
	// Flours
	['spelt flour'],
	['all-purpose flour', 'all purpose flour', 'flour'],
	['flour'],
	// Misc
	['burger bun', 'burger buns'],
	['egg', 'eggs'],
	['sugar'],
	['mustard'],
	['vinegar'],
	['vodka'],
	['noodle', 'noodles'],
	['rice noodle', 'rice noodles'],
	['olive oil', 'extra virgin olive oil', 'extra-virgin olive oil'],
];
