export const UNITS = [
	['bag', 'bags'],
	['box', 'boxes'],
	['clove', 'cloves'],
	['can', 'cans'],
	['cup', 'cups', 'c', 'c.'],
	['foot', 'feet', 'ft', 'ft.'],
	['gallon', 'gallons', 'gal', 'gal.'],
	['gram', 'grams', 'g', 'g.'],
	['inch', 'inches', 'in', 'in.'],
	['kilogram', 'kilograms', 'kg', 'kg.'],
	['liter', 'liters', 'l'],
	['milligram', 'milligrams', 'mg', 'mg.'],
	['milliliter', 'milliliters', 'ml', 'mL', 'ml.'],
	['ounce', 'ounces', 'oz', 'oz.'],
	['package', 'packages', 'pkg', 'pkgs'],
	['piece', 'pieces', 'pcs', 'pcs.'],
	['pinch', 'pinches'],
	['pint', 'pints', 'pt', 'pt.'],
	['pound', 'pounds', 'lb', 'lb.', 'lbs', 'lbs.'],
	['quart', 'quarts', 'qt', 'qt.', 'qts', 'qts.'],
	['quart', 'quarts', 'qt', 'qt.'],
	['slice', 'slices'],
	['sprig', 'sprigs'],
	['stick', 'sticks'],
	['tablespoon', 'tablespoons', 'tbsp', 'tbsp.'],
	['teaspoon', 'teaspoons', 'tsp', 'tsp.'],
];
