export const UNITS = [
	['bag', 'bags'],
	['box', 'boxes'],
	['can', 'cans'],
	['clove', 'cloves'],
	['cup', 'cups', 'c', 'c.'],
	['ft', 'ft', 'foot', 'feet', 'ft.'],
	['g', 'g', 'gram', 'grams', 'g.'],
	['gal', 'gal', 'gallon', 'gallons', 'gal.'],
	['in', 'in', 'inch', 'inches', 'in.'],
	['kg', 'kg', 'kilogram', 'kilograms', 'kg.'],
	['l', 'l', 'liter', 'liters'],
	['lb', 'lbs', 'pound', 'pounds', 'lb.', 'lbs.'],
	['mg', 'mg', 'milligram', 'milligrams', 'mg.'],
	['ml', 'ml', 'milliliter', 'milliliters', 'ml.'],
	['oz', 'oz', 'ounce', 'ounces', 'oz.'],
	['package', 'packages', 'pkg', 'pkgs'],
	['piece', 'pieces', 'pcs', 'pcs.'],
	['pinch', 'pinches'],
	['pt', 'pt', 'pint', 'pints', 'pt.'],
	['qt', 'qts', 'quart', 'quarts', 'qt.', 'qts.'],
	['slice', 'slices'],
	['sprig', 'sprigs'],
	['stick', 'sticks'],
	['tablespoon', 'tablespoons', 'tbsp', 'tbsp.'],
	['teaspoon', 'teaspoons', 'tsp', 'tsp.'],
];
