// Data from https://www.eufic.org/en/explore-seasonal-fruit-and-vegetables-in-europe

export enum Month {
	January = 1,
	February = 2,
	March = 3,
	April = 4,
	May = 5,
	June = 6,
	July = 7,
	August = 8,
	September = 9,
	October = 10,
	November = 11,
	December = 12,
}

export const SEASONS: Record<string, Month[]> = {
	[`apple`]: [Month.September, Month.October],
	[`strawberry`]: [Month.May, Month.June, Month.July],
	[`apricot`]: [Month.July, Month.August],
	[`blackcurrant`]: [Month.June, Month.July, Month.August],
	[`cherry`]: [Month.June, Month.July, Month.August],
	[`blackberry`]: [Month.July, Month.August, Month.September],
	[`blueberry`]: [Month.July, Month.August, Month.September],
	[`gooseberry`]: [Month.July, Month.August],
	[`pear`]: [Month.August, Month.October],
	[`elderberry`]: [Month.September, Month.October],
	[`quince`]: [Month.September, Month.October, Month.November],
	[`watermelon`]: [Month.September],
	[`pumpkin`]: [Month.October, Month.November],
	[`grape`]: [Month.September, Month.October],
	[`plum`]: [Month.July, Month.August, Month.September],
	[`carrot`]: [
		Month.July,
		Month.August,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`mangold`]: [Month.July, Month.August, Month.September],
	[`onion`]: [Month.July, Month.August, Month.September, Month.October],
	[`pea`]: [Month.July, Month.August],
	[`runner bean`]: [Month.July, Month.August, Month.September, Month.October],
	[`sweet corn`]: [Month.July, Month.August, Month.September, Month.October],
	[`raspberry`]: [Month.June, Month.July, Month.August],
	[`asparagus`]: [Month.April, Month.May, Month.June],
	[`beetroot`]: [
		Month.January,
		Month.February,
		Month.March,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`bell pepper`]: [
		Month.April,
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`black radish`]: [
		Month.January,
		Month.February,
		Month.November,
		Month.December,
	],
	[`brussels sprout`]: [
		Month.January,
		Month.February,
		Month.October,
		Month.November,
		Month.December,
	],
	[`broad bean`]: [Month.June, Month.July],
	[`green bean`]: [
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
		Month.November,
	],
	[`broccoli`]: [
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`zucchini`]: [Month.June, Month.July, Month.August, Month.September],
	[`pak choi`]: [Month.June, Month.July, Month.August, Month.September],
	[`fennel`]: [Month.June, Month.July, Month.August, Month.September],
	[`cauliflower`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`celery`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
	],
	[`cucumber`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
	],
	[`kohlrabi`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`lettuce`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`celeriac`]: [
		Month.January,
		Month.February,
		Month.March,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`chicory`]: [
		Month.January,
		Month.February,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`chinese cabbage`]: [
		Month.January,
		Month.February,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`kale`]: [
		Month.January,
		Month.February,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`lamb’s lettuce`]: [
		Month.January,
		Month.February,
		Month.September,
		Month.October,
	],
	[`parsley root`]: [Month.January, Month.February, Month.December],
	[`parsnip`]: [Month.January, Month.February, Month.November, Month.December],
	[`potato`]: [
		Month.January,
		Month.February,
		Month.March,
		Month.April,
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`red cabbage`]: [
		Month.January,
		Month.February,
		Month.March,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`radish`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
	],
	[`rucola`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`tomato`]: [
		Month.May,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
	],
	[`turnip`]: [
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
	],
	[`scallion`]: [Month.May, Month.June, Month.July, Month.August],
	[`rhubarb`]: [Month.March, Month.April, Month.May, Month.June, Month.July],
	[`rutabaga`]: [Month.January, Month.February, Month.November, Month.December],
	[`salsify`]: [
		Month.January,
		Month.February,
		Month.October,
		Month.November,
		Month.December,
	],
	[`spinach`]: [
		Month.March,
		Month.April,
		Month.May,
		Month.September,
		Month.October,
		Month.November,
	],
	[`savoy cabbage`]: [
		Month.January,
		Month.February,
		Month.June,
		Month.July,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
	[`white cabbage`]: [
		Month.January,
		Month.February,
		Month.March,
		Month.June,
		Month.July,
		Month.August,
		Month.September,
		Month.October,
		Month.November,
		Month.December,
	],
};
